# Generated by Django 4.0 on 2022-05-17 14:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_shopuser_activation_key_expires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='social_link',
            field=models.CharField(blank=True, max_length=128, verbose_name='Facebook Link'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 14, 50, 9, 878931, tzinfo=utc)),
        ),
    ]
