# Generated by Django 4.0 on 2022-05-18 11:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_shopuserprofile_social_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 20, 11, 53, 47, 243594, tzinfo=utc)),
        ),
    ]
